---
# file: roles/ilo/tasks/power.yml
- name: Resetting server to apply changes and upgrade firmware (REST API)
  uri:
    url: "https://{{ item }}/rest/v1/systems/1"
    method: PATCH
    user: "{{ ilo_user }}"
    password: "{{ ilo_password }}"
    force_basic_auth: true
    validate_certs: false
    body: '{"Action": "Reset", "ResetType": "ForceRestart"}'
    body_format: json
  with_items: "{{ ilo_addr.results | map(attribute='ansible_facts.ipmi') | list }}"
  when: (ilo_firmware >= '250')

- name: Resetting server to apply changes and upgrade firmware (IPMI)
  command:
    ipmitool -I lanplus -H {{ item }} -U {{ ilo_user }} -P {{ ilo_password }} chassis power reset
  with_items: "{{ ilo_addr.results | map(attribute='ansible_facts.ipmi') | list }}"
  when: (ilo_firmware < '250')
